eureka: 
  client: 
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance: 
    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"
    prefer-ip-address: true
spring: 
  boot: 
    admin: 
      client: 
        url: 
          - http://admin:admin@localhost:8761/admin
    zipkin: 
      base-url: http://localhost:9411
