eureka: 
  client: 
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8761/eureka
spring: 
  boot: 
    admin: 
      client: 
        url: 
          - http:/localhost:8761/admin
    zipkin: 
      base-url: http://localhost:9411
